INSERT INTO products (sku,name,department,category,price_cents,stock,status,tag,color,featured,created_at,updated_at) VALUES
('FX-U-TEE','Motion Tee','Unisex','Tops',4200,120,'active','','red',1,strftime('%s','now'),strftime('%s','now')),
('FX-U-JOG','Flex Joggers','Unisex','Bottoms',7800,64,'active','New','blue',1,strftime('%s','now'),strftime('%s','now')),
('FX-U-HOD','Gusset Hoodie','Unisex','Tops',9600,9,'active','','ink',1,strftime('%s','now'),strftime('%s','now')),
('FX-U-SHO','Stretch Shorts','Unisex','Bottoms',3800,210,'active','Bestseller','volt',1,strftime('%s','now'),strftime('%s','now')),
('FX-U-JKT','Articulated Jacket','Unisex','Outerwear',12800,4,'active','New','red',1,strftime('%s','now'),strftime('%s','now')),
('FX-U-BSL','Flat-Seam Base Layer','Unisex','Tops',5400,45,'active','','blue',1,strftime('%s','now'),strftime('%s','now')),
('FX-M-TEE','Men''s Motion Tee','Men','Tops',4200,80,'active','New','red',0,strftime('%s','now'),strftime('%s','now')),
('FX-M-HOD','Men''s Gusset Hoodie','Men','Tops',9600,40,'active','','ink',0,strftime('%s','now'),strftime('%s','now')),
('FX-M-BSL','Men''s Base Layer','Men','Tops',5400,55,'active','','blue',0,strftime('%s','now'),strftime('%s','now')),
('FX-M-JOG','Men''s Flex Joggers','Men','Bottoms',7800,70,'active','Bestseller','blue',0,strftime('%s','now'),strftime('%s','now')),
('FX-M-SHO','Men''s Stretch Shorts','Men','Bottoms',3800,90,'active','','volt',0,strftime('%s','now'),strftime('%s','now')),
('FX-M-JKT','Men''s Articulated Jacket','Men','Outerwear',12800,25,'active','New','red',0,strftime('%s','now'),strftime('%s','now')),
('FX-W-TEE','Women''s Motion Tee','Women','Tops',4200,85,'active','New','red',0,strftime('%s','now'),strftime('%s','now')),
('FX-W-HOD','Women''s Gusset Hoodie','Women','Tops',9200,35,'active','','ink',0,strftime('%s','now'),strftime('%s','now')),
('FX-W-BSL','Women''s Base Layer','Women','Tops',5200,60,'active','','blue',0,strftime('%s','now'),strftime('%s','now')),
('FX-W-LEG','Women''s Flex Leggings','Women','Bottoms',7400,95,'active','Bestseller','blue',0,strftime('%s','now'),strftime('%s','now')),
('FX-W-SHO','Women''s Stretch Shorts','Women','Bottoms',3600,100,'active','','volt',0,strftime('%s','now'),strftime('%s','now')),
('FX-W-JKT','Women''s Flex Wrap Jacket','Women','Outerwear',12400,20,'active','New','red',0,strftime('%s','now'),strftime('%s','now')),
('FX-K-TEE','Mini Motion Tee','Kids','Tops',2800,75,'active','New','red',0,strftime('%s','now'),strftime('%s','now')),
('FX-K-BSL','Kids'' Base Layer','Kids','Tops',3400,50,'active','','blue',0,strftime('%s','now'),strftime('%s','now')),
('FX-K-JOG','Kids'' Flex Joggers','Kids','Bottoms',4600,60,'active','Bestseller','volt',0,strftime('%s','now'),strftime('%s','now')),
('FX-K-SHO','Kids'' Stretch Shorts','Kids','Bottoms',2600,80,'active','','blue',0,strftime('%s','now'),strftime('%s','now')),
('FX-K-JKT','Kids'' Packable Jacket','Kids','Outerwear',6800,30,'active','','red',0,strftime('%s','now'),strftime('%s','now'));

INSERT INTO drops (name,description,release_date,created_at) VALUES
('All-Weather Shell','A taped-seam shell built over the Articulated Jacket pattern, sized for layering.','Oct 14',strftime('%s','now')),
('Flex Knit Trainer','Our first footwear piece: a knit upper on a flexible sole built for lateral movement.','Oct 28',strftime('%s','now')),
('Recovery Jogger 2.0','A softer, brushed-back version of the Flex Joggers for rest days and travel.','Nov 11',strftime('%s','now')),
('Kids'' Flex Collection','An expanded Kids'' line: tops, bottoms and a packable shell in three new colors.','Dec 2',strftime('%s','now'));
