name = "flex-shop"
compatibility_date = "2026-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "flex-db"
database_id = "20b98e68-141d-4536-8c9f-7e8162e54f38"   # printed by: npx wrangler d1 create flex-db
